name: chat
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  sizer: ^2.0.15
  equatable: ^2.0.7
  lazy_load_scrollview: ^1.3.0
  socket_io_client: ^3.0.2
  connectivity_plus: ^6.1.1
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  device_info_plus: ^11.2.0
  http_parser: ^4.1.1
  encrypt: ^5.0.3
  flutter_native_splash: ^2.4.3

flutter_assets:
  assets_path: assets/
  output_path: lib/src/config/constant
  filename: assets.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash/
    - fonts/

  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/font.ttf
