name: chat
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  dio: ^5.5.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  sizer: ^2.0.15
  equatable: ^2.0.5
  lazy_load_scrollview: ^1.3.0
  socket_io_client: ^2.0.3+1
  connectivity_plus: ^6.0.4
  intl: ^0.19.0
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0

flutter_assets:
  assets_path: assets/
  output_path: lib/src/config/constant
  filename: assets.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - fonts/

  # example:
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: fonts/font.ttf
