name: chat
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  sizer: ^2.0.15
  equatable: ^2.0.7
  lazy_load_scrollview: ^1.3.0
  socket_io_client: ^3.0.2
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  device_info_plus: ^11.3.2
  http_parser: ^4.1.2
  encrypt: ^5.0.3
  flutter_native_splash: ^2.4.5
  go_router: ^14.8.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  http: ^1.3.0
  path_provider: ^2.1.5
  image: ^4.5.4

flutter_assets:
  assets_path: assets/
  output_path: lib/src/config/constant
  filename: assets.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash/
    - fonts/

  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/font.ttf
